<a href="https://colab.research.google.com/github/nimethon/class-07-assignment/blob/main/class_07_assignment_7_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 7.1

**TASK-01 validating manual calculation**

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = {'age':[21,20,22,22,23,21,25,30,31], 'Income(k)': [60,55,60,61,65,62,65,70,68] }
df = pd.DataFrame(data)
df.head(10)

age  Income(k)
0   21         60
1   20         55
2   22         60
3   22         61
4   23         65
5   21         62
6   25         65
7   30         70
8   31         68

In [ ]:
x = df['age']
y = df['Income(k)']
x

0    21
1    20
2    22
3    22
4    23
5    21
6    25
7    30
8    31
Name: age, dtype: int64

In [ ]:
input_x = int(input('enter new age: '))

enter new age: 22


In [ ]:
distance = np.abs(x - input_x)
sorted = np.argsort(distance)
sorted

0    2
1    3
2    0
3    4
4    5
5    1
6    6
7    7
8    8
Name: age, dtype: int64

In [ ]:
KNN = y[sorted[:3]]
KNN

2    60
3    61
0    60
Name: Income(k), dtype: int64

In [ ]:
income = np.mean(KNN)
income

60.333333333333336

In [ ]:
new_col = pd.DataFrame({'age': [input_x], 'Income(k)': [income]}) #creating a new Dataframe about age, income
df = pd.concat([df, new_col], ignore_index = True)    # concat , we may use for the exisitng DataFrame with the new
df

age  Income(k)
0   21  60.000000
1   20  55.000000
2   22  60.000000
3   22  61.000000
4   23  65.000000
5   21  62.000000
6   25  65.000000
7   30  70.000000
8   31  68.000000
9   22  60.333333

In [ ]:
df.to_csv("income_age_data.csv" , index=False)

#Linear Regression Sklearn

In [ ]:
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df1 = pd.read_csv("income_age_data.csv")
df1.drop(df1.tail(1).index, inplace=True)
#df1 = df1.iloc[:-1] another way to delete last row
df1

age  Income(k)
0   21       60.0
1   20       55.0
2   22       60.0
3   22       61.0
4   23       65.0
5   21       62.0
6   25       65.0
7   30       70.0
8   31       68.0

In [ ]:
reg = LinearRegression()
reg.fit(df1[['age']], df1 [['Income(k)']])
predicted = reg.predict([[22]])
predicted

array([[60.97068966]])

In [ ]:
compare = predicted - income
compare

array([[0.63735632]])

In [54]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=3)
x = df1[['age']]
y = df1[['Income(k)']]
neigh.fit(x,y)
neigh.predict([[22]])

array([[60.33333333]])